##############
## DATABASE ##
##############
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: RM93518
    password: 190304
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

############
## TOKEN  ##
############
access:
  token:
    value: $aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNjQyODc6OiRhYWNoX2MxZTMxYzljLWI2M2ItNDM4YS05Njc3LWFjYjVjZjRiODQxYw==

############
## CLIENT ##
############
request:
  host:
    value: https://sandbox.asaas.com/api/v3
  endpoint:
    client:
      creat_client:
        value: /customers