##############
## DATABASE ##
##############
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: ${oracle-username-fiap}
    password: ${oracle-password-fiap}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

############
## TOKEN  ##
############
access:
  token:
    value: ${access_token_assas}

############
## CLIENT ##
############
request:
  host:
    value: https://sandbox.asaas.com/api/v3
  endpoint:
    client:
      creat_client:
        value: /customers